---
- name: Ensure base packages are installed
  apt:
    name:
      - mc
      - screen
      - smartmontools
      - curl
      - git
      - apt-key
      - gpg
      - lsb-release
      - apt-transport-https
      - ca-certificates
      - htop
      - btop
      - ethtool
      - nmap
      - ncdu
    state: present
    update_cache: yes

- name: Configure cron email redirection for root
  lineinfile:
    path: /etc/crontab
    regexp: '^MAILTO='
    line: "MAILTO={{ cron_email }}"
    create: yes
