all:
  hosts:
    osiris:
      ansible_host: 192.168.3.10
      ansible_user: root
      bridge_interface: eno1 # Change to the physical interface you want to bridge

      bridge_config:
        address: 192.168.3.10
        netmask: 255.255.255.0
        gateway: 192.168.3.1
        dns_nameservers:
          - 1.1.1.1
          - 8.8.8.8