export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"

plugins=(git docker docker-compose z)

source $ZSH/oh-my-zsh.sh

# Suggestions
if [ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# Syntax Highlighting
if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Inline completion
autoload -Uz compinit
compinit

# Prompt config
export PROMPT='%F{green}%n@%m%f:%F{blue}%~%f %# '
