---
- name: Install dependencies
  apt:
    name:
      - zsh
      - git
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
    update_cache: yes

- name: Set Zsh as default shell for users
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  loop: "{{ ansible_users }}"

- name: Deploy .zshrc for users
  copy:
    src: zshrc
    dest: "/home/{{ item }}/.zshrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop: "{{ ansible_users }}"
  when: item != 'root'

- name: Deploy .zshrc for root
  copy:
    src: zshrc
    dest: "/root/.zshrc"
    owner: root
    group: root
    mode: '0644'

- include_tasks: install-oh-my-zsh.yml
  loop: "{{ ansible_users }}"