---
- name: Install dependencies
  apt:
    name:
      - zsh
      - git
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
    update_cache: yes

- name: Install Oh My Zsh for all users
  block:
    - name: Ensure Oh My Zsh is installed for user {{ item }}
      become_user: "{{ item }}"
      shell: |
        export HOME=$(getent passwd {{ item }} | cut -d: -f6)
        if [ ! -d "$HOME/.oh-my-zsh" ]; then
          RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi
      args:
        executable: /bin/bash
  loop: "{{ ansible_users }}"

- name: Set Zsh as default shell for users
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  loop: "{{ ansible_users }}"

- name: Deploy .zshrc for users
  copy:
    src: zshrc
    dest: "/home/{{ item }}/.zshrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop: "{{ ansible_users }}"
  when: item != 'root'

- name: Deploy .zshrc for root
  copy:
    src: zshrc
    dest: "/root/.zshrc"
    owner: root
    group: root
    mode: '0644'
