---
- name: Ensure dependencies are installed
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Create keyrings directory (if missing)
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download NVIDIA GPG key (ASCII armored)
  get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /tmp/nvidia.asc
    mode: '0644'

- name: Convert NVIDIA GPG key to GPG binary format
  command: >
    gpg --dearmor -o /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia.asc
  args:
    creates: /etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg

- name: Create NVIDIA APT repo list with signed-by (workaround for Debian 12)
  copy:
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    content: |
      deb [signed-by=/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/amd64 /

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install NVIDIA container toolkit
  apt:
    name: nvidia-container-toolkit
    state: present

- name: Add non-free repository to sources list
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free non-free-firmware"
    state: present
    filename: non-free

- name: Install Nvidia drivers
  ansible.builtin.apt:
    update_cache: yes
    name:
      - firmware-misc-nonfree
      - nvidia-driver
      - nvtop
    state: latest

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: true
