---
- name: Ensure dependencies are installed
  apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Download NVIDIA GPG key
  get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    mode: '0644'

- name: Download NVIDIA container toolkit repo list
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    mode: '0644'

- name: Update repo list to include signed-by in NVIDIA repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    regexp: '^deb https://'
    line: 'deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /'
    backrefs: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install NVIDIA container toolkit
  apt:
    name:
      - nvidia-container-toolkit
    state: present

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: true
