---
- name: Ensure directory for keyrings exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download NVIDIA GPG key to keyring
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    mode: '0644'

- name: Download NVIDIA container toolkit repo list with signed-by
  ansible.builtin.shell: |
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's|^deb https://|deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://|' > /etc/apt/sources.list.d/nvidia-container-toolkit.list
  args:
    executable: /bin/bash

- name: Install NVIDIA Docker packages
  ansible.builtin.apt:
    name:
      - nvidia-docker2
    state: present
    update_cache: yes

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
