---
- name: Ensure dependencies are installed
  apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Download NVIDIA GPG key
  get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    mode: '0644'

- name: Create NVIDIA APT repo list with signed-by (workaround for Debian 12)
  copy:
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    content: |
      deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/amd64 /

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install NVIDIA container toolkit
  apt:
    name: nvidia-container-toolkit
    state: present

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: true
