---
- name: Download NVIDIA GPG key
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    mode: '0644'

- name: Download NVIDIA container toolkit repo list
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    mode: '0644'

- name: Add NVIDIA Docker repo GPG key
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Install NVIDIA Docker packages
  ansible.builtin.apt:
    name:
      - nvidia-docker2
    state: present
    update_cache: yes

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
