---
- name: Install SnapRAID from APT
  apt:
    name: snapraid
    state: present

- name: Clone snapraid-runner repo
  git:
    repo: https://github.com/Chronial/snapraid-runner.git
    dest: /opt/snapraid-runner
    version: master

- name: Deploy snapraid-runner config
  template:
    src: snapraid-runner.conf.j2
    dest: /opt/snapraid-runner/snapraid-runner.conf
    mode: '0644'

- name: Run snapraid-runner daily
  cron:
    name: "Run snapraid-runner"
    job: "python3 /opt/snapraid-runner/snapraid-runner.py -c /opt/snapraid-runner/snapraid-runner.conf"
    minute: "30"
    hour: "2"
