---
- name: Install SnapRAID from APT
  apt:
    name: snapraid
    state: present

- name: Symlink snapraid-runner to /usr/local/bin
  file:
    src: /opt/snapraid-runner/snapraid-runner
    dest: /usr/local/bin/snapraid-runner
    state: link
    mode: '0755'

- name: Deploy snapraid-runner config
  template:
    src: snapraid-runner.conf.j2
    dest: /etc/snapraid-runner.conf
    mode: '0644'

- name: Run snapraid-runner daily
  cron:
    name: "Run snapraid-runner"
    job: "/usr/local/bin/snapraid-runner"
    minute: "30"
    hour: "2"
