---
- name: Setup a default debian server
  hosts: all
  become: true

  vars:
    #example: "value"

  pre_tasks:
    - name: Load sensitive vars from external file
      include_vars: .env.yml
      when: lookup('file', '.env.yml', errors='ignore') is defined

  roles:
    - common
    - docker
    - docker-nvidia
    - mergerfs
    - snapraid
    - powersave
    - qemu-kvm
