- name: Ensure bridge-utils is installed
  ansible.builtin.apt:
    name: bridge-utils
    state: present
    update_cache: yes

- name: Ensure /etc/network/interfaces.d directory exists
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory       

- name: Disable {{ bridge_interface }} DHCP config in /etc/network/interfaces
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    regexp: '^(allow-hotplug {{ bridge_interface }}|iface {{ bridge_interface }} inet dhcp)'
    state: absent
    backrefs: yes

- name: Create static bridge configuration for br0
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/br0.cfg
    content: |
      auto br0
      iface br0 inet static
          address {{ bridge_config.address }}
          netmask {{ bridge_config.netmask }}
          gateway {{ bridge_config.gateway }}
          {% if bridge_config.dns_nameservers is defined %}
          dns-nameservers {{ bridge_config.dns_nameservers | join(' ') }}
          {% endif %}
          bridge_ports {{ bridge_interface }}
          bridge_stp off
          bridge_fd 0
          bridge_maxwait 0
    owner: root
    group: root
    mode: '0644'

- name: Configure physical interface {{ bridge_interface }} to manual mode
  ansible.builtin.copy:
    dest: /etc/network/interfaces.d/{{ bridge_interface }}.cfg
    content: |
      allow-hotplug {{ bridge_interface }}
      iface {{ bridge_interface }} inet manual
    owner: root
    group: root
    mode: '0644'

- name: Restart networking to bring up br0
  shell: |
    ifdown {{ bridge_interface }} || true
    ifup {{ bridge_interface }} || true
    ifdown br0 || true
    ifup br0
