---
- name: Install Cockpit and cockpit-machines
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-machines
    state: present
    update_cache: yes

- name: Ensure cockpit.socket is enabled and running
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
